### ISSUE TITLE
error while running built commandlines

### ISSUE THREAD

**Issue by Nitinsn29** [Rongxi-Zhang/radar-robotcar-dataset-ros#1]
while runnimg this command
rosdep install src --from-paths -i -y
getting this ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies: radar_robotcar_dataset_ros: Cannot locate rosdep definition for [camera_models]
![Screenshot from 2022-07-12 16-34-47](https://user-images.githubusercontent.com/106977025/178476121-f6fc6fdd-912a-4dcc-876d-c4c205befb24.png)

**Comment by Rongxi-Zhang** [comment]
Oh, the ROS package named camera_models is unnecessary for this project, it needs to be commented out before this project will compile.
In the CMakeLists.txt :
find_package(catkin REQUIRED COMPONENTS
  rospy
  roscpp
  std_msgs
  geometry_msgs
  nav_msgs
  tf
  cv_bridge
  **camera_models**
  image_transport
  pcl_ros
  pcl_conversions
  message_generation
)and

and int the package.xml
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>image_transport</build_depend>
  **<build_depend>camera_models</build_depend>**

  <exec_depend>roscpp</exec_depend>
  <exec_depend>image_transport</exec_depend>
  **<exec_depend>camera_models</exec_depend>**

  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>

**Comment by Nitinsn29** [comment]
thanks for the help

**Comment by Rongxi-Zhang** [comment]
Oh, the ROS package named camera_modela is unnecessary for this project, it
needs to be commented out before this project will compile.
In the CMakeLists.txt :
find_package(catkin REQUIRED COMPONENTS
rospy
roscpp
std_msgs
geometry_msgs
nav_msgs
tf
cv_bridge
* camera_models*
image_transport
pcl_ros
pcl_conversions
message_generation
)and and int the package.xml
<buildtool_depend>catkin</buildtool_depend>
<build_depend>roscpp</build_depend>
<build_depend>image_transport</build_depend>
* <build_depend>camera_models</build_depend>*
<exec_depend>roscpp</exec_depend>
<exec_depend>image_transport</exec_depend>
* <exec_depend>camera_models</exec_depend>*
<build_depend>message_generation</build_depend>
<exec_depend>message_runtime</exec_depend>Thank you for your attention to
this project.

Nitinsn29 ***@***.***> 于2022年7月12日周二 19:05写道：
