### ISSUE TITLE
Build errors - rosdep definitions

### ISSUE THREAD

**Issue by ram-bhaskara** [Rongxi-Zhang/radar-robotcar-dataset-ros#2]
I'm trying to catkin_make as suggested in the build instructions. 

while running this command rosdep install src --from-paths -i -y 
I'm getting this error message: the following packages/stacks could not have their rosdep keys resolved to system dependencies: radar_robotcar_dataset_ros: Cannot locate rosdep definition for [camera_models] . 

Please help!

**Comment by Rongxi-Zhang** [comment]
https://github.com/Rongxi-Zhang/radar-robotcar-dataset-ros/issues/1#issue-1301901338
